### ISSUE TITLE
How to source javascript that can be used w/in key stories

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#142]
Question - 

If we want to use d3 in a key-story div, how does that happen? The way the page is set up, our div isn't created when the functions would be called. I chatted w/ Lindsay about this yesterday, and she pointed out [this reference](https://stackoverflow.com/questions/16823757/d3-selectelement-not-working-when-code-above-the-html-element) which covers what is going on. 

For example, if I add this snippet to the build_map.js (note I would do this stuff in a different file, but bear with me...):
```js
var svgStates = d3.select(".key-story-plot")
  .append("svg")
  .attr('viewBox', '0 0 1000 300')
  .attr('preserveAspectRatio', 'xMidYMid');
svgStates.append("g")
  .append('rect')
    .attr('fill','red')
    .attr('height',"300")
    .attr('width',"1000");
```
 I would expect a red rectangle to appear in the first key story div. It doesn't, but it will appear if I run that same snippet in console after the page is loaded. 

I know they key story divs don't appear the same way after the recent PR was merged, but this question is still relevant. I can work around this, but wondering what our preferred method for sourcing function calls that depend on DOM elements like these divs. The build_map gets around this by creating the first div of the page by using d3.

**Comment by lindsaycarr** [comment]
Would it make sense to add it as a resource to a `section` and then the `publish.section` function could handle it much like the full page one does? So, insert `<script src="js/keystoryfig.js?_c=2932527" type="text/javascript"></script>` down by that div?

**Comment by lindsaycarr** [comment]
I just tried adding 

```
  -
    id: key_stories
    template: layout/templates/key_stories.mustache
    publisher: section
    depends: "keystoryfig"
    context:
      resources: "keystoryfig"
  -
    id: keystoryfig
    location: "js/keystoryfig.js"
    mimetype: application/javascript
```
to the viz.yaml and then sticking this into the mustache file. Seems to have broken something because now there are no divs.
```
{{#resources }}
    {{{ . }}}
{{/resources }}
```
